### ISSUE TITLE
Did you try the chemical solution?

### ISSUE THREAD

**Issue by deftdawg** [james481/cat-trainer#1]
Spray the area with juice made from ground orange peels & put up a scratch post somewhere else...

**Comment by james481** [comment]
We didn't try any chemical solutions, but do have various scratching posts around the house for them.

**Comment by deftdawg** [comment]
If you've ever peeled an Orange and sprayed yourself breaking the peel, you know it has a slight eye-watering burn to it (sort of like cutting Onions), cats are much better smellers than humans (somewhere between 2x and 20x better), so that burning sensation is more intense for them.

Anyway, it works for when they spray/mark areas, not sure about scratching...  Had a very old kitty in her 20s who would go a little crazy at night howling and spraying in the basement, we hit her hotspots with citrus spray and it would snap her out of her night-time episodes.   Maybe something of use someday.   

Still it's impressive you managed to make a cat spray turret.   All the best.
